app = 'almuerzos-peru'
primary_region = 'gru'

[build]
  dockerfile = './docker/images/Dockerfile.prod'

[env]
  PORT = "3000"
  HOST = "0.0.0.0"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  interval = "15s"
  timeout  = "5s"
  method   = "GET"
  path     = "/api/v1/health"
  protocol = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
