services:
  postgres:
    image: postgres:15-alpine
    container_name: almuerzos-postgres
    environment:
      POSTGRES_DB: db_almuerzos_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - almuerzos-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d db_almuerzos_dev" ]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build:
      context: ../../
      dockerfile: docker/images/Dockerfile.dev
    container_name: almuerzos-api
    env_file:
      - ../../config/environments/development.docker.env
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - almuerzos-network
    volumes:
      - ../../:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/v1/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local
    name: almuerzos_postgres_dev_data

networks:
  almuerzos-network:
    driver: bridge
    name: almuerzos_dev_network
