#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch_name=$(git symbolic-ref --short HEAD)

# Cambia esto según tus reglas
if [[ ! "$branch_name" =~ ^(feature|fix|hotfix|chore|test|refactor|docs)\/[a-z0-9._-]+$ ]]; then
  echo "❌ Nombre de rama inválido: '$branch_name'"
  echo "➡️  Usa el formato: tipo/nombre-ejemplo (ej: feat/login-page)"
  exit 1
fi

echo "✅ Nombre de rama válido: $branch_name"
